INSERT INTO region VALUES (1, "Arica y Parinacota");
INSERT INTO region VALUES (2, "Tarapacá");
INSERT INTO region VALUES (3, "Antofagasta");
INSERT INTO region VALUES (4, "Atacama");
INSERT INTO region VALUES (5, "Coquimbo");
INSERT INTO region VALUES (6, "Valparaíso");
INSERT INTO region VALUES (7, "Libertador General Bernardo O'Higgins");
INSERT INTO region VALUES (8, "Maule");
INSERT INTO region VALUES (9, "BioBío");
INSERT INTO region VALUES (10, "La Araucanía");
INSERT INTO region VALUES (11, "Los Ríos");
INSERT INTO region VALUES (12, "Los Lagos");
INSERT INTO region VALUES (13, "Aisén del General Carlos Ibáñez del Campo");
INSERT INTO region VALUES (14, "Magallanes y Antártica Chilena");
INSERT INTO region VALUES (15, "Región Metropolitana de Santiago");

INSERT INTO provincia VALUES (1, 1, "Arica");
INSERT INTO provincia VALUES (2, 1, "Parinacota");
INSERT INTO provincia VALUES (3, 2, "Iquique");
INSERT INTO provincia VALUES (4, 2, "Tamarugal");
INSERT INTO provincia VALUES (5, 3, "Antofagasta");
INSERT INTO provincia VALUES (6, 3, "El Loa");
INSERT INTO provincia VALUES (7, 3, "Tocopilla");
INSERT INTO provincia VALUES (8, 4, "Copiapó");
INSERT INTO provincia VALUES (9, 4, "Chañaral");
INSERT INTO provincia VALUES (10, 4, "Huasco");
INSERT INTO provincia VALUES (11, 5, "Elqui");
INSERT INTO provincia VALUES (12, 5, "Choapa");
INSERT INTO provincia VALUES (13, 5, "Limarí");
INSERT INTO provincia VALUES (14, 6, "Valparaíso");
INSERT INTO provincia VALUES (15, 6, "Isla de Pascua");
INSERT INTO provincia VALUES (16, 6, "Los Andes");
INSERT INTO provincia VALUES (17, 6, "Petorca");
INSERT INTO provincia VALUES (18, 6, "Quillota");
INSERT INTO provincia VALUES (19, 6, "San Antonio");
INSERT INTO provincia VALUES (20, 6, "San Felipe de Aconcagua");
INSERT INTO provincia VALUES (21, 6, "Marga Marga");
INSERT INTO provincia VALUES (22, 7, "Cachapoal");
INSERT INTO provincia VALUES (23, 7, "Cardenal Caro");
INSERT INTO provincia VALUES (24, 7, "Colchagua");
INSERT INTO provincia VALUES (25, 8, "Talca");
INSERT INTO provincia VALUES (26, 8, "Cauquenes");
INSERT INTO provincia VALUES (27, 8, "Curicó");
INSERT INTO provincia VALUES (28, 8, "Linares");
INSERT INTO provincia VALUES (29, 9, "Concepción");
INSERT INTO provincia VALUES (30, 9, "Arauco");
INSERT INTO provincia VALUES (31, 9, "Biobío");
INSERT INTO provincia VALUES (32, 9, "Ñuble");
INSERT INTO provincia VALUES (33, 10, "Cautín");
INSERT INTO provincia VALUES (34, 10, "Malleco");
INSERT INTO provincia VALUES (35, 11, "Valdivia");
INSERT INTO provincia VALUES (36, 11, "Ranco");
INSERT INTO provincia VALUES (37, 12, "Llanquihue");
INSERT INTO provincia VALUES (38, 12, "Chiloé");
INSERT INTO provincia VALUES (39, 12, "Osorno");
INSERT INTO provincia VALUES (40, 12, "Palena");
INSERT INTO provincia VALUES (41, 13, "Coyhaique");
INSERT INTO provincia VALUES (42, 13, "Aisén");
INSERT INTO provincia VALUES (43, 13, "Capitán Prat");
INSERT INTO provincia VALUES (44, 13, "General Carrera");
INSERT INTO provincia VALUES (45, 14, "Magallanes");
INSERT INTO provincia VALUES (46, 14, "Antártica Chilena");
INSERT INTO provincia VALUES (47, 14, "Tierra del Fuego");
INSERT INTO provincia VALUES (48, 14, "Ultima Esperanza");
INSERT INTO provincia VALUES (49, 15, "Santiago");
INSERT INTO provincia VALUES (50, 15, "Cordillera");
INSERT INTO provincia VALUES (51, 15, "Chacabuco");
INSERT INTO provincia VALUES (52, 15, "Maipo");
INSERT INTO provincia VALUES (53, 15, "Melipilla");
INSERT INTO provincia VALUES (54, 15, "Talagante");


INSERT INTO comuna VALUES (1, 1, "Arica");
INSERT INTO comuna VALUES (2, 1, "Camarones");
INSERT INTO comuna VALUES (3, 2, "Putre");
INSERT INTO comuna VALUES (4, 2, "General Lagos");
INSERT INTO comuna VALUES (5, 3, "Iquique");
INSERT INTO comuna VALUES (6, 3, "Alto Hospicio");
INSERT INTO comuna VALUES (7, 4, "Pozo Almonte");
INSERT INTO comuna VALUES (8, 4, "Camiña");
INSERT INTO comuna VALUES (9, 4, "Colchane");
INSERT INTO comuna VALUES (10, 4, "Huara");
INSERT INTO comuna VALUES (11, 4, "Pica");
INSERT INTO comuna VALUES (12, 5, "Antofagasta");
INSERT INTO comuna VALUES (13, 5, "Mejillones");
INSERT INTO comuna VALUES (14, 5, "Sierra Gorda");
INSERT INTO comuna VALUES (15, 5, "Taltal");
INSERT INTO comuna VALUES (16, 6, "Calama");
INSERT INTO comuna VALUES (17, 6, "Ollagüe");
INSERT INTO comuna VALUES (18, 6, "San Pedro de Atacama");
INSERT INTO comuna VALUES (19, 7, "Tocopilla");
INSERT INTO comuna VALUES (20, 7, "María Elena");
INSERT INTO comuna VALUES (21, 8, "Copiapó");
INSERT INTO comuna VALUES (22, 8, "Caldera");
INSERT INTO comuna VALUES (23, 8, "Tierra Amarilla");
INSERT INTO comuna VALUES (24, 9, "Chañaral");
INSERT INTO comuna VALUES (25, 9, "Diego de Almagro");
INSERT INTO comuna VALUES (26, 10, "Vallenar");
INSERT INTO comuna VALUES (27, 10, "Alto del Carmen");
INSERT INTO comuna VALUES (28, 10, "Freirina");
INSERT INTO comuna VALUES (29, 10, "Huasco");
INSERT INTO comuna VALUES (30, 11, "La Serena");
INSERT INTO comuna VALUES (31, 11, "Coquimbo");
INSERT INTO comuna VALUES (32, 11, "Andacollo");
INSERT INTO comuna VALUES (33, 11, "La Higuera");
INSERT INTO comuna VALUES (34, 11, "Paiguano");
INSERT INTO comuna VALUES (35, 11, "Vicuña");
INSERT INTO comuna VALUES (36, 12, "Illapel");
INSERT INTO comuna VALUES (37, 12, "Canela");
INSERT INTO comuna VALUES (38, 12, "Los Vilos");
INSERT INTO comuna VALUES (39, 12, "Salamanca");
INSERT INTO comuna VALUES (40, 13, "Ovalle");
INSERT INTO comuna VALUES (41, 13, "Combarbalá");
INSERT INTO comuna VALUES (42, 13, "Monte Patria");
INSERT INTO comuna VALUES (43, 13, "Punitaqui");
INSERT INTO comuna VALUES (44, 13, "Río Hurtado");
INSERT INTO comuna VALUES (45, 14, "Valparaíso");
INSERT INTO comuna VALUES (46, 14, "Casablanca");
INSERT INTO comuna VALUES (47, 14, "Concón");
INSERT INTO comuna VALUES (48, 14, "Juan Fernández");
INSERT INTO comuna VALUES (49, 14, "Puchuncaví");
INSERT INTO comuna VALUES (50, 14, "Quintero");
INSERT INTO comuna VALUES (51, 14, "Viña del Mar");
INSERT INTO comuna VALUES (52, 15, "Isla de Pascua");
INSERT INTO comuna VALUES (53, 16, "Los Andes");
INSERT INTO comuna VALUES (54, 16, "Calle Larga");
INSERT INTO comuna VALUES (55, 16, "Rinconada");
INSERT INTO comuna VALUES (56, 16, "San Esteban");
INSERT INTO comuna VALUES (57, 17, "La Ligua");
INSERT INTO comuna VALUES (58, 17, "Cabildo");
INSERT INTO comuna VALUES (59, 17, "Papudo");
INSERT INTO comuna VALUES (60, 17, "Petorca");
INSERT INTO comuna VALUES (61, 17, "Zapallar");
INSERT INTO comuna VALUES (62, 18, "Quillota");
INSERT INTO comuna VALUES (63, 18, "Calera");
INSERT INTO comuna VALUES (64, 18, "Hijuelas");
INSERT INTO comuna VALUES (65, 18, "La Cruz");
INSERT INTO comuna VALUES (66, 18, "Nogales");
INSERT INTO comuna VALUES (67, 19, "San Antonio");
INSERT INTO comuna VALUES (68, 19, "Algarrobo");
INSERT INTO comuna VALUES (69, 19, "Cartagena");
INSERT INTO comuna VALUES (70, 19, "El Quisco");
INSERT INTO comuna VALUES (71, 19, "El Tabo");
INSERT INTO comuna VALUES (72, 19, "Santo Domingo");
INSERT INTO comuna VALUES (73, 20, "San Felipe");
INSERT INTO comuna VALUES (74, 20, "Catemu");
INSERT INTO comuna VALUES (75, 20, "Llaillay");
INSERT INTO comuna VALUES (76, 20, "Panquehue");
INSERT INTO comuna VALUES (77, 20, "Putaendo");
INSERT INTO comuna VALUES (78, 20, "Santa María");
INSERT INTO comuna VALUES (79, 21, "Limache");
INSERT INTO comuna VALUES (80, 21, "Quilpué");
INSERT INTO comuna VALUES (81, 21, "Villa Alemana");
INSERT INTO comuna VALUES (82, 21, "Olmué");
INSERT INTO comuna VALUES (83, 22, "Rancagua");
INSERT INTO comuna VALUES (84, 22, "Codegua");
INSERT INTO comuna VALUES (85, 22, "Coinco");
INSERT INTO comuna VALUES (86, 22, "Coltauco");
INSERT INTO comuna VALUES (87, 22, "Doñihue");
INSERT INTO comuna VALUES (88, 22, "Graneros");
INSERT INTO comuna VALUES (89, 22, "Las Cabras");
INSERT INTO comuna VALUES (90, 22, "Machalí");
INSERT INTO comuna VALUES (91, 22, "Malloa");
INSERT INTO comuna VALUES (92, 22, "Mostazal");
INSERT INTO comuna VALUES (93, 22, "Olivar");
INSERT INTO comuna VALUES (94, 22, "Peumo");
INSERT INTO comuna VALUES (95, 22, "Pichidegua");
INSERT INTO comuna VALUES (96, 22, "Quinta de Tilcoco");
INSERT INTO comuna VALUES (97, 22, "Rengo");
INSERT INTO comuna VALUES (98, 22, "Requínoa");
INSERT INTO comuna VALUES (99, 22, "San Vicente");
INSERT INTO comuna VALUES (100, 23, "Pichilemu");
INSERT INTO comuna VALUES (101, 23, "La Estrella");
INSERT INTO comuna VALUES (102, 23, "Litueche");
INSERT INTO comuna VALUES (103, 23, "Marchihue");
INSERT INTO comuna VALUES (104, 23, "Navidad");
INSERT INTO comuna VALUES (105, 23, "Paredones");
INSERT INTO comuna VALUES (106, 24, "San Fernando");
INSERT INTO comuna VALUES (107, 24, "Chépica");
INSERT INTO comuna VALUES (108, 24, "Chimbarongo");
INSERT INTO comuna VALUES (109, 24, "Lolol");
INSERT INTO comuna VALUES (110, 24, "Nancagua");
INSERT INTO comuna VALUES (111, 24, "Palmilla");
INSERT INTO comuna VALUES (112, 24, "Peralillo");
INSERT INTO comuna VALUES (113, 24, "Placilla");
INSERT INTO comuna VALUES (114, 24, "Pumanque");
INSERT INTO comuna VALUES (115, 24, "Santa Cruz");
INSERT INTO comuna VALUES (116, 25, "Talca");
INSERT INTO comuna VALUES (117, 25, "Constitución");
INSERT INTO comuna VALUES (118, 25, "Curepto");
INSERT INTO comuna VALUES (119, 25, "Empedrado");
INSERT INTO comuna VALUES (120, 25, "Maule");
INSERT INTO comuna VALUES (121, 25, "Pelarco");
INSERT INTO comuna VALUES (122, 25, "Pencahue");
INSERT INTO comuna VALUES (123, 25, "Río Claro");
INSERT INTO comuna VALUES (124, 25, "San Clemente");
INSERT INTO comuna VALUES (125, 25, "San Rafael");
INSERT INTO comuna VALUES (126, 26, "Cauquenes");
INSERT INTO comuna VALUES (127, 26, "Chanco");
INSERT INTO comuna VALUES (128, 26, "Pelluhue");
INSERT INTO comuna VALUES (129, 27, "Curicó");
INSERT INTO comuna VALUES (130, 27, "Hualañé");
INSERT INTO comuna VALUES (131, 27, "Licantén");
INSERT INTO comuna VALUES (132, 27, "Molina");
INSERT INTO comuna VALUES (133, 27, "Rauco");
INSERT INTO comuna VALUES (134, 27, "Romeral");
INSERT INTO comuna VALUES (135, 27, "Sagrada Familia");
INSERT INTO comuna VALUES (136, 27, "Teno");
INSERT INTO comuna VALUES (137, 27, "Vichuquén");
INSERT INTO comuna VALUES (138, 28, "Linares");
INSERT INTO comuna VALUES (139, 28, "Colbún");
INSERT INTO comuna VALUES (140, 28, "Longaví");
INSERT INTO comuna VALUES (141, 28, "Parral");
INSERT INTO comuna VALUES (142, 28, "Retiro");
INSERT INTO comuna VALUES (143, 28, "San Javier");
INSERT INTO comuna VALUES (144, 28, "Villa Alegre");
INSERT INTO comuna VALUES (145, 28, "Yerbas Buenas");
INSERT INTO comuna VALUES (146, 29, "Concepción");
INSERT INTO comuna VALUES (147, 29, "Coronel");
INSERT INTO comuna VALUES (148, 29, "Chiguayante");
INSERT INTO comuna VALUES (149, 29, "Florida");
INSERT INTO comuna VALUES (150, 29, "Hualqui");
INSERT INTO comuna VALUES (151, 29, "Lota");
INSERT INTO comuna VALUES (152, 29, "Penco");
INSERT INTO comuna VALUES (153, 29, "San Pedro de la Paz");
INSERT INTO comuna VALUES (154, 29, "Santa Juana");
INSERT INTO comuna VALUES (155, 29, "Talcahuano");
INSERT INTO comuna VALUES (156, 29, "Tomé");
INSERT INTO comuna VALUES (157, 29, "Hualpén");
INSERT INTO comuna VALUES (158, 30, "Lebu");
INSERT INTO comuna VALUES (159, 30, "Arauco");
INSERT INTO comuna VALUES (160, 30, "Cañete");
INSERT INTO comuna VALUES (161, 30, "Contulmo");
INSERT INTO comuna VALUES (162, 30, "Curanilahue");
INSERT INTO comuna VALUES (163, 30, "Los Alamos");
INSERT INTO comuna VALUES (164, 30, "Tirúa");
INSERT INTO comuna VALUES (165, 31, "Los Angeles");
INSERT INTO comuna VALUES (166, 31, "Antuco");
INSERT INTO comuna VALUES (167, 31, "Cabrero");
INSERT INTO comuna VALUES (168, 31, "Laja");
INSERT INTO comuna VALUES (169, 31, "Mulchén");
INSERT INTO comuna VALUES (170, 31, "Nacimiento");
INSERT INTO comuna VALUES (171, 31, "Negrete");
INSERT INTO comuna VALUES (172, 31, "Quilaco");
INSERT INTO comuna VALUES (173, 31, "Quilleco");
INSERT INTO comuna VALUES (174, 31, "San Rosendo");
INSERT INTO comuna VALUES (175, 31, "Santa Bárbara");
INSERT INTO comuna VALUES (176, 31, "Tucapel");
INSERT INTO comuna VALUES (177, 31, "Yumbel");
INSERT INTO comuna VALUES (178, 31, "Alto Biobío");
INSERT INTO comuna VALUES (179, 32, "Chillán");
INSERT INTO comuna VALUES (180, 32, "Bulnes");
INSERT INTO comuna VALUES (181, 32, "Cobquecura");
INSERT INTO comuna VALUES (182, 32, "Coelemu");
INSERT INTO comuna VALUES (183, 32, "Coihueco");
INSERT INTO comuna VALUES (184, 32, "Chillán Viejo");
INSERT INTO comuna VALUES (185, 32, "El Carmen");
INSERT INTO comuna VALUES (186, 32, "Ninhue");
INSERT INTO comuna VALUES (187, 32, "Ñiquén");
INSERT INTO comuna VALUES (188, 32, "Pemuco");
INSERT INTO comuna VALUES (189, 32, "Pinto");
INSERT INTO comuna VALUES (190, 32, "Portezuelo");
INSERT INTO comuna VALUES (191, 32, "Quillón");
INSERT INTO comuna VALUES (192, 32, "Quirihue");
INSERT INTO comuna VALUES (193, 32, "Ránquil");
INSERT INTO comuna VALUES (194, 32, "San Carlos");
INSERT INTO comuna VALUES (195, 32, "San Fabián");
INSERT INTO comuna VALUES (196, 32, "San Ignacio");
INSERT INTO comuna VALUES (197, 32, "San Nicolás");
INSERT INTO comuna VALUES (198, 32, "Treguaco");
INSERT INTO comuna VALUES (199, 32, "Yungay");
INSERT INTO comuna VALUES (200, 33, "Temuco");
INSERT INTO comuna VALUES (201, 33, "Carahue");
INSERT INTO comuna VALUES (202, 33, "Cunco");
INSERT INTO comuna VALUES (203, 33, "Curarrehue");
INSERT INTO comuna VALUES (204, 33, "Freire");
INSERT INTO comuna VALUES (205, 33, "Galvarino");
INSERT INTO comuna VALUES (206, 33, "Gorbea");
INSERT INTO comuna VALUES (207, 33, "Lautaro");
INSERT INTO comuna VALUES (208, 33, "Loncoche");
INSERT INTO comuna VALUES (209, 33, "Melipeuco");
INSERT INTO comuna VALUES (210, 33, "Nueva Imperial");
INSERT INTO comuna VALUES (211, 33, "Padre Las Casas");
INSERT INTO comuna VALUES (212, 33, "Perquenco");
INSERT INTO comuna VALUES (213, 33, "Pitrufquén");
INSERT INTO comuna VALUES (214, 33, "Pucón");
INSERT INTO comuna VALUES (215, 33, "Saavedra");
INSERT INTO comuna VALUES (216, 33, "Teodoro Schmidt");
INSERT INTO comuna VALUES (217, 33, "Toltén");
INSERT INTO comuna VALUES (218, 33, "Vilcún");
INSERT INTO comuna VALUES (219, 33, "Villarrica");
INSERT INTO comuna VALUES (220, 33, "Cholchol");
INSERT INTO comuna VALUES (221, 34, "Angol");
INSERT INTO comuna VALUES (222, 34, "Collipulli");
INSERT INTO comuna VALUES (223, 34, "Curacautín");
INSERT INTO comuna VALUES (224, 34, "Ercilla");
INSERT INTO comuna VALUES (225, 34, "Lonquimay");
INSERT INTO comuna VALUES (226, 34, "Los Sauces");
INSERT INTO comuna VALUES (227, 34, "Lumaco");
INSERT INTO comuna VALUES (228, 34, "Purén");
INSERT INTO comuna VALUES (229, 34, "Renaico");
INSERT INTO comuna VALUES (230, 34, "Traiguén");
INSERT INTO comuna VALUES (231, 34, "Victoria");
INSERT INTO comuna VALUES (232, 35, "Valdivia");
INSERT INTO comuna VALUES (233, 35, "Corral");
INSERT INTO comuna VALUES (234, 35, "Lanco");
INSERT INTO comuna VALUES (235, 35, "Los Lagos");
INSERT INTO comuna VALUES (236, 35, "Máfil");
INSERT INTO comuna VALUES (237, 35, "Mariquina");
INSERT INTO comuna VALUES (238, 35, "Paillaco");
INSERT INTO comuna VALUES (239, 35, "Panguipulli");
INSERT INTO comuna VALUES (240, 36, "La Unión");
INSERT INTO comuna VALUES (241, 36, "Futrono");
INSERT INTO comuna VALUES (242, 36, "Lago Ranco");
INSERT INTO comuna VALUES (243, 36, "Río Bueno");
INSERT INTO comuna VALUES (244, 37, "Puerto Montt");
INSERT INTO comuna VALUES (245, 37, "Calbuco");
INSERT INTO comuna VALUES (246, 37, "Cochamó");
INSERT INTO comuna VALUES (247, 37, "Fresia");
INSERT INTO comuna VALUES (248, 37, "Frutillar");
INSERT INTO comuna VALUES (249, 37, "Los Muermos");
INSERT INTO comuna VALUES (250, 37, "Llanquihue");
INSERT INTO comuna VALUES (251, 37, "Maullín");
INSERT INTO comuna VALUES (252, 37, "Puerto Varas");
INSERT INTO comuna VALUES (253, 38, "Castro");
INSERT INTO comuna VALUES (254, 38, "Ancud");
INSERT INTO comuna VALUES (255, 38, "Chonchi");
INSERT INTO comuna VALUES (256, 38, "Curaco de Vélez");
INSERT INTO comuna VALUES (257, 38, "Dalcahue");
INSERT INTO comuna VALUES (258, 38, "Puqueldón");
INSERT INTO comuna VALUES (259, 38, "Queilén");
INSERT INTO comuna VALUES (260, 38, "Quellón");
INSERT INTO comuna VALUES (261, 38, "Quemchi");
INSERT INTO comuna VALUES (262, 38, "Quinchao");
INSERT INTO comuna VALUES (263, 39, "Osorno");
INSERT INTO comuna VALUES (264, 39, "Puerto Octay");
INSERT INTO comuna VALUES (265, 39, "Purranque");
INSERT INTO comuna VALUES (266, 39, "Puyehue");
INSERT INTO comuna VALUES (267, 39, "Río Negro");
INSERT INTO comuna VALUES (268, 39, "San Juan de la Costa");
INSERT INTO comuna VALUES (269, 39, "San Pablo");
INSERT INTO comuna VALUES (270, 40, "Chaitén");
INSERT INTO comuna VALUES (271, 40, "Futaleufú");
INSERT INTO comuna VALUES (272, 40, "Hualaihué");
INSERT INTO comuna VALUES (273, 40, "Palena");
INSERT INTO comuna VALUES (274, 41, "Coyhaique");
INSERT INTO comuna VALUES (275, 41, "Lago Verde");
INSERT INTO comuna VALUES (276, 42, "Aisén");
INSERT INTO comuna VALUES (277, 42, "Cisnes");
INSERT INTO comuna VALUES (278, 42, "Guaitecas");
INSERT INTO comuna VALUES (279, 43, "Cochrane");
INSERT INTO comuna VALUES (280, 43, "O'Higgins");
INSERT INTO comuna VALUES (281, 43, "Tortel");
INSERT INTO comuna VALUES (282, 44, "Chile Chico");
INSERT INTO comuna VALUES (283, 44, "Río Ibáñez");
INSERT INTO comuna VALUES (284, 45, "Punta Arenas");
INSERT INTO comuna VALUES (285, 45, "Laguna Blanca");
INSERT INTO comuna VALUES (286, 45, "Río Verde");
INSERT INTO comuna VALUES (287, 45, "San Gregorio");
INSERT INTO comuna VALUES (288, 46, "Cabo de Hornos (Ex-Navarino)");
INSERT INTO comuna VALUES (289, 46, "Antártica");
INSERT INTO comuna VALUES (290, 47, "Porvenir");
INSERT INTO comuna VALUES (291, 47, "Primavera");
INSERT INTO comuna VALUES (292, 47, "Timaukel");
INSERT INTO comuna VALUES (293, 48, "Natales");
INSERT INTO comuna VALUES (294, 48, "Torres del Paine");
INSERT INTO comuna VALUES (295, 49, "Santiago");
INSERT INTO comuna VALUES (296, 49, "Cerrillos");
INSERT INTO comuna VALUES (297, 49, "Cerro Navia");
INSERT INTO comuna VALUES (298, 49, "Conchalí");
INSERT INTO comuna VALUES (299, 49, "El Bosque");
INSERT INTO comuna VALUES (300, 49, "Estación Central");
INSERT INTO comuna VALUES (301, 49, "Huechuraba");
INSERT INTO comuna VALUES (302, 49, "Independencia");
INSERT INTO comuna VALUES (303, 49, "La Cisterna");
INSERT INTO comuna VALUES (304, 49, "La Florida");
INSERT INTO comuna VALUES (305, 49, "La Granja");
INSERT INTO comuna VALUES (306, 49, "La Pintana");
INSERT INTO comuna VALUES (307, 49, "La Reina");
INSERT INTO comuna VALUES (308, 49, "Las Condes");
INSERT INTO comuna VALUES (309, 49, "Lo Barnechea");
INSERT INTO comuna VALUES (310, 49, "Lo Espejo");
INSERT INTO comuna VALUES (311, 49, "Lo Prado");
INSERT INTO comuna VALUES (312, 49, "Macul");
INSERT INTO comuna VALUES (313, 49, "Maipú");
INSERT INTO comuna VALUES (314, 49, "Ñuñoa");
INSERT INTO comuna VALUES (315, 49, "Pedro Aguirre Cerda");
INSERT INTO comuna VALUES (316, 49, "Peñalolén");
INSERT INTO comuna VALUES (317, 49, "Providencia");
INSERT INTO comuna VALUES (318, 49, "Pudahuel");
INSERT INTO comuna VALUES (319, 49, "Quilicura");
INSERT INTO comuna VALUES (320, 49, "Quinta Normal");
INSERT INTO comuna VALUES (321, 49, "Recoleta");
INSERT INTO comuna VALUES (322, 49, "Renca");
INSERT INTO comuna VALUES (323, 49, "San Joaquín");
INSERT INTO comuna VALUES (324, 49, "San Miguel");
INSERT INTO comuna VALUES (325, 49, "San Ramón");
INSERT INTO comuna VALUES (326, 49, "Vitacura");
INSERT INTO comuna VALUES (327, 50, "Puente Alto");
INSERT INTO comuna VALUES (328, 50, "Pirque");
INSERT INTO comuna VALUES (329, 50, "San José de Maipo");
INSERT INTO comuna VALUES (330, 51, "Colina");
INSERT INTO comuna VALUES (331, 51, "Lampa");
INSERT INTO comuna VALUES (332, 51, "Tiltil");
INSERT INTO comuna VALUES (333, 52, "San Bernardo");
INSERT INTO comuna VALUES (334, 52, "Buin");
INSERT INTO comuna VALUES (335, 52, "Calera de Tango");
INSERT INTO comuna VALUES (336, 52, "Paine");
INSERT INTO comuna VALUES (337, 53, "Melipilla");
INSERT INTO comuna VALUES (338, 53, "Alhué");
INSERT INTO comuna VALUES (339, 53, "Curacaví");
INSERT INTO comuna VALUES (340, 53, "María Pinto");
INSERT INTO comuna VALUES (341, 53, "San Pedro");
INSERT INTO comuna VALUES (342, 54, "Talagante");
INSERT INTO comuna VALUES (343, 54, "El Monte");
INSERT INTO comuna VALUES (344, 54, "Isla de Maipo");
INSERT INTO comuna VALUES (345, 54, "Padre Hurtado");
INSERT INTO comuna VALUES (346, 54, "Peñaflor");