usuario(id, rol_id, username, password, rut, dv, nombre, telefono, email, created_at, updated_at, deleted_at)
rol(id, nombre)
permiso(id, nombre)
permiso_rol(permiso_id, rol_id)
catastrofe(id, usuario_id, tipo_catastrofe_id, locacion_id, descripcion, fecha_catastrofe)
tipo_catastrofe(id, nombre)
comuna(id, provincia_id, nombre)
provincia(id, region_id, nombre)
region(id, nombre)
locacion(id, comuna_id, latitude, longitude)
medida(id, usuario_id, aprobada, objetivos, descripcion)
evento_a_beneficio(id, medida_id, locacion_id, fecha, horario_inicio, horario_termino, actividades, created_at, updated_at)
registro_actividad(id, usuario_id, tipo_actividad_id, created_at, updated_at)
tipo_actividad(id, nombre)
voluntariado(id, medida_id, locacion_id, actividad_voluntariado_id, fecha_inicio, fecha_termino, cantidad_voluntarios, created_at, updated_at)
actividad_voluntariado(id, nombre)
voluntario(id, usuario_id, voluntariado_id, finalizado, created_at, updated_at)
rnv(id, rut, dv, nombre, email, disponible, created_at, updated_at)
centro_acopio(id, medida_id, locacion_id, estado_id, fecha_inicio, fecha_termino, created_at, updated_at)
estado(id, nombre)
bien(id, usuario_id, centro_acopio_id, medicion_id, tipo, cantidad)
medicion(id, nombre)
donacion(id, medida_id, titular, rut_destinatario, nombre_banco, tipo_cuenta, cuenta, fecha_inicio, fecha_termino, created_at, updated_at)
deposito(id, usuario_id, donacion_id, fecha, monto)
gasto(id, usuario_id, fecha, monto, proposito)
comentario(id, medida_id, usuario_id, descripcion, created_at, updated_at)
